# Giai đoạn build (build stage)
FROM node:18-alpine AS builder

WORKDIR /app

# Sao chép các tệp package
COPY manager/frontend/package*.json ./
RUN npm ci

# Sao chép mã nguồn
COPY manager/frontend/ .

# Build ứng dụng
RUN npm run build

RUN ls -a 

# Giai đoạn chạy (runtime stage)
FROM nginx:alpine

# Sao chép kết quả build
COPY --from=builder /app/dist /usr/share/nginx/html

# Sao chép tệp diagnose.js
COPY manager/frontend/diagnose.js /usr/share/nginx/html/

# Sao chép cấu hình nginx
COPY manager/frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]